### ISSUE TITLE
BodyDef Compatibility

### ISSUE THREAD

**Issue by HR-SP** [emipa606/PlasteelSurgery#1]
As promised, a new issue ;)

What I'd need you to test is adding a class

```C#
public class SurgeryDef : RecipeDef { }
```

then, in the recipe_surgery.xml, change any RecipeDef to SurgeryDef and see if it works.

```XML
<SurgeryDef ParentName="PS_IncreaseBeautyBase">
  <defName>PS_IncreaseBeautyBasic</defName>
...
```

**Comment by emipa606** [comment]
solved in later commit
